#!/bin/bash -x

docker images

# show meta data
docker inspect $IMAGE_NAME

# show each layer size
docker history $IMAGE_NAME

# build sample project
cd test_projects/SampleProject
docker run --rm -v `pwd`:/project mingc/android-build-box bash -c 'cd /project; ./gradlew build'

