#!/bin/bash
#

# Pull exist image to boost build
# This does not work well because the base image may update.
# docker pull sampingan/android

docker info
docker images

# Remove exist images to release disk space.
docker rmi $(docker images | grep -v IMAGE | awk '{print $3}')
docker image prune -a -f

docker images
